project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    background: black
    left:
      - text: Hands-on Exercise
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on.html"
      - text: In-class Exercise 
        menu: 
          - text: 'In-class Exercise 1'
            href: "In-class.html"
    right:
      - href: about.qmd
        text: Home 
      - href: about.qmd
        text: About 


format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

